CMAKE_MINIMUM_REQUIRED(VERSION 3.25 FATAL_ERROR)
PROJECT(TEST_PACKAGE_A)

SET(PACK_NAME "test-package-a")
SET(SHARED_TARGET_NAME "${PACK_NAME}-shared")
SET(PACK_NAMESPACE "${SHARED_TARGET_NAME}::")
SET(PACKAGE_VERSION 1.0.0)

FIND_PACKAGE(CMLIB COMPONENTS CMDEF CMUTIL)

CMDEF_ADD_LIBRARY(
    LIBRARY_GROUP ${PACK_NAME}
    TYPE SHARED
    SOURCES src/pack_a.cpp
    INCLUDE_DIRECTORIES "${CMAKE_CURRENT_SOURCE_DIR}/include/"
    INSTALL_INCLUDE_DIRECTORIES "include/"
    VERSION ${PACKAGE_VERSION}
)

CMDEF_INSTALL(
    TARGET ${SHARED_TARGET_NAME}
    NAMESPACE ${PACK_NAMESPACE}
)

CMDEF_PACKAGE(
    MAIN_TARGET ${SHARED_TARGET_NAME}
    VERSION ${PACKAGE_VERSION}
)
