CMAKE_MINIMUM_REQUIRED(VERSION 3.25 FATAL_ERROR)
PROJECT(TEST_PACKAGES)

OPTION(USE_PACKAGE_A "Use test-package-a" OFF)
OPTION(USE_PACKAGE_B "Use test-package-b" OFF)
OPTION(USE_PACKAGE_C "Use test-package-c" OFF)
OPTION(USE_PACKAGE_D "Use test-package-d" OFF)
OPTION(USE_PACKAGE_E "Use test-package-e" OFF)
OPTION(USE_APP_A "Use test-app-a" OFF)
OPTION(USE_APP_B "Use test-app-b" OFF)
OPTION(USE_APP_C "Use test-app-c" OFF)

if(USE_PACKAGE_A)
    MESSAGE(STATUS "Building test-package-a")
    ADD_SUBDIRECTORY(test-package-a)
elseif(USE_PACKAGE_B)
    MESSAGE(STATUS "Building test-package-b")
    ADD_SUBDIRECTORY(test-package-b)
elseif(USE_PACKAGE_C)
    MESSAGE(STATUS "Building test-package-c")
    ADD_SUBDIRECTORY(test-package-c)
elseif(USE_PACKAGE_D)
    MESSAGE(STATUS "Building test-package-d")
    ADD_SUBDIRECTORY(test-package-d)
elseif(USE_PACKAGE_E)
    MESSAGE(STATUS "Building test-package-e")
    ADD_SUBDIRECTORY(test-package-e)
elseif(USE_APP_A)
    MESSAGE(STATUS "Building test-app-a")
    ADD_SUBDIRECTORY(test-app-a)
elseif(USE_APP_B)
    MESSAGE(STATUS "Building test-app-b")
    ADD_SUBDIRECTORY(test-app-b)
elseif(USE_APP_C)
    MESSAGE(STATUS "Building test-app-c")
    ADD_SUBDIRECTORY(test-app-c)
endif()