CMAKE_MINIMUM_REQUIRED(VERSION 3.25 FATAL_ERROR)
PROJECT(TEST_PACKAGES)

OPTION(USE_PACKAGE_1 "Use test_package_1" OFF)
OPTION(USE_PACKAGE_2 "Use test_package_2" OFF)
OPTION(USE_PACKAGE_3 "Use test_package_3" OFF)
OPTION(USE_PACKAGE_4 "Use test_package_4" OFF)
OPTION(USE_PACKAGE_4 "Use test_package_5" OFF)
OPTION(USE_APP_1 "Use test_app_1" OFF)
OPTION(USE_APP_2 "Use test_app_2" OFF)

if(USE_PACKAGE_1)
    MESSAGE(STATUS "Building test_package_2")
    ADD_SUBDIRECTORY(test_package_1)
elseif(USE_PACKAGE_2)
    MESSAGE(STATUS "Building test_package_2")
    ADD_SUBDIRECTORY(test_package_2)
elseif(USE_PACKAGE_3)
    MESSAGE(STATUS "Building test_package_3")
    ADD_SUBDIRECTORY(test_package_3)
elseif(USE_PACKAGE_4)
    MESSAGE(STATUS "Building test_package_4")
    ADD_SUBDIRECTORY(test_package_4)
elseif(USE_PACKAGE_5)
    MESSAGE(STATUS "Building test_package_5")
    ADD_SUBDIRECTORY(test_package_5)
elseif(USE_APP_1)
    MESSAGE(STATUS "Building test_app_1")
    ADD_SUBDIRECTORY(test_app_1)
elseif(USE_APP_2)
    MESSAGE(STATUS "Building test_app_2")
    ADD_SUBDIRECTORY(test_app_2)
endif()