CMAKE_MINIMUM_REQUIRED(VERSION 3.25 FATAL_ERROR)
PROJECT(TEST_APP_A)

SET(APP_NAME "test-app-a")
SET(APP_NAMESPACE "${APP_NAME}::")
SET(APP_VERSION 1.0.0)

FIND_PACKAGE(CMLIB COMPONENTS CMDEF CMUTIL REQUIRED)

CMDEF_ADD_EXECUTABLE(
    TARGET ${APP_NAME}
    SOURCES main.cpp
    VERSION ${APP_VERSION}
)

CMDEF_INSTALL(
    TARGET ${APP_NAME}
    NAMESPACE ${APP_NAMESPACE}
)

CMDEF_PACKAGE(
    MAIN_TARGET ${APP_NAME}
    VERSION ${APP_VERSION}
)
